pretrain: '' # pretrained state dict path

enc_dec:
  n_stages: 4
  n_resblocks: 1
  init_channels: 3
  max_channels: 512
  deform_stages: []

train_dataset:
  manifest_path: null
  scaling_factor: ${enc_dec.n_stages}
  resize_dim: 1024 # The smaller dim will be resized to the given size, and the larger will be resized with a similar fraction.
  augment: true
  batch_size: 4
  shuffle: true
  num_workers: 4

validation_dataset:
  manifest_path: null
  scaling_factor: ${enc_dec.n_stages}
  resize_dim: 1024
  augment: false
  batch_size: 4
  shuffle: true
  num_workers: 4

test_dataset:
  manifest_path: null
  scaling_factor: ${enc_dec.n_stages}
  resize_dim: 1024
  augment: false
  batch_size: 4
  shuffle: true
  num_workers: 4

optim:
  lr: 0.005
  betas: [0.9, 0.98]
  weight_decay: 1e-4