pretrain: null # pretrained state dict path

enc_dec:
  n_stages: 6
  n_resblocks: 1
  in_channels: 3
  out_channels: 512

bottleneck:
  feat_in: 512
  feat_out: 512
  patch_size: 3
  n_layers: 12
  d_model: 512
  n_heads: 8
  ff_expansion_factor: 4
  dropout: 0.1

train_dataset:
  manifest_path: null
  scaling_factor: ${enc_dec.n_stages}
  patch_size: ${bottleneck.patch_size}
  batch_size: 4
  shuffle: true
  num_workers: 4

validation_dataset:
  manifest_path: null
  scaling_factor: ${enc_dec.n_stages}
  patch_size: ${bottleneck.patch_size}
  batch_size: 4
  shuffle: true
  num_workers: 4

test_dataset:
  manifest_path: null
  scaling_factor: ${enc_dec.n_stages}
  patch_size: ${bottleneck.patch_size}
  batch_size: 4
  shuffle: true
  num_workers: 4

optim:
  name: adamw
  lr: 0.005
  betas: [0.9, 0.98]
  weight_decay: 1e-3