enc_dec:
  n_stages: 6
  n_resblocks: 1
  in_channels: 3
  out_channels: 512

bottleneck:
  feat_in: 512
  feat_out: 512
  patch_size: 3
  n_layers: 12
  d_model: 512
  n_heads: 8
  ff_expansion_factor: 4
  dropout: 0.1

train_dataset:
  root_dir: 'examples/data'
  extensions: ['.jpg', '.png']
  scaling_factor: ${enc_dec.n_stages}
  patch_size: ${bottleneck.patch_size}
  batch_size: 4
  shuffle: true
  num_workers: 0

validation_dataset:
  root_dir: 'examples/data'
  extensions: ['.jpg', '.png']
  scaling_factor: ${enc_dec.n_stages}
  patch_size: ${bottleneck.patch_size}
  batch_size: 4
  shuffle: true
  num_workers: 4

masking:
  rectangle_masking:
    num_mask: 0 # number of masks
    height: 0.1 # compared to image's height
    width: 0.1 # compared to image's width
    mask_value: 0.0

  pixel_masking:
    ratio: 0.0
    mask_value: 0.0

  noise_masking:
    mean: 0.0
    std: 0.1

optim:
  name: adamw
  lr: 0.005
  betas: [0.9, 0.98]
  weight_decay: 1e-3